services:
  ui:
    build: ./roman-numerals-ui
    image: ui
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./roman-numerals-ui:/ui
      - /ui/node_modules
    networks:
      - webappnetwork

  api:
    build: ./roman-numerals-api
    image: api
    restart: always
    ports:
      - "3600:3600"
    volumes:
      - ./roman-numerals-api:/api
      - /api/node_modules
    depends_on:
      - mongodb
    networks:
      - webappnetwork

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
      - ./roman-numerals-db:/data/db
    ports:
      - 27017:27017
    networks:
      - webappnetwork
    command:
      - '--logpath'
      - '/var/log/mongodb/mongod.log'

networks:
  webappnetwork:
    driver: bridge